num=int(input('Please enter first number: '))
num_2=int(input('Please enter second number: '))
division=int(num/num_2)
resto=int(num%num_2)
print(f"{num} divided by {num_2} is {division} with a residue of {resto}")